### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by gressus** [khasang/Cachoeira#1]

**Comment by gressus** [comment]
![2015-08-25 1 54 29](https://cloud.githubusercontent.com/assets/8287232/9454654/53cca65e-4acc-11e5-8232-5a408b9069bd.png)
var 1

**Comment by gressus** [comment]
![2015-08-25 1 54 36](https://cloud.githubusercontent.com/assets/8287232/9454658/5ee21e0c-4acc-11e5-84cd-84cd0d5569a6.png)
var 2

**Comment by gressus** [comment]
![2015-08-25 15 38 14](https://cloud.githubusercontent.com/assets/8287232/9466701/6f55cca2-4b3f-11e5-9d27-0c00b81f1ed7.png)
var 3

**Comment by gressus** [comment]
![2015-08-25 15 52 48](https://cloud.githubusercontent.com/assets/8287232/9467018/61a23166-4b41-11e5-92ab-e9770156df3b.png)

var 4

**Comment by gressus** [comment]
![2015-08-25 15 54 51](https://cloud.githubusercontent.com/assets/8287232/9467099/eb0e1abe-4b41-11e5-83e0-921230277eb0.png)

**Comment by Raenar4k** [comment]
var 6

![c2](https://cloud.githubusercontent.com/assets/13849790/9563385/7393c5da-4e82-11e5-951f-25788b0f1382.png)

**Comment by Raenar4k** [comment]
var 7
![c3](https://cloud.githubusercontent.com/assets/13849790/9564354/af803ca0-4ea4-11e5-909f-7821694d9dc3.png)

**Comment by Raenar4k** [comment]
var 8
![c4](https://cloud.githubusercontent.com/assets/13849790/9564355/c0646d20-4ea4-11e5-81ea-4ecb75686c66.png)

**Comment by Raenar4k** [comment]
var 9
![c4_1](https://cloud.githubusercontent.com/assets/13849790/9564359/cb9da044-4ea4-11e5-8d63-f5ec28f51db4.png)
