### ISSUE TITLE
Пакет Model IProject/Project

### ISSUE THREAD

**Issue by GeorgeSemenov** [khasang/Cachoeira#14]
Создать интерфейс IProject со следующими полями 
+save(target: String)
+load(source: String)
+getName(): String
+setName(name: String)
+getStart(): Date
+setStart(start:Date)
+getFinish(): Date
+setFinish(finish: Date)
+getTaskList(): List<ITask>//Интерфейс ITask будет создаваться в другой задаче
+setTaskList(tasks: List<ITask>)

Создать класс Project , который реализует интерфейс IProject
private переменные
-name String;(пока по умолчанию всегда = "Проект")
-start: Date (пока не инициализируемая переменная)
-finish: Date (пока не инициализируемая переменная)
-tasks: List<ITask>
public методы
+save(target: String)//реализуется "выбросом" исключения (как вариант   throw new IllegalArgumentException("Не реализован метод save класса Project");
+load(source: String)//Метод должен подгружать данные проекта по умолчанию из defaultProject.xml 
+exportResources(target: String)//реализуется "выбросом" исключения (как метод save)
+importResources(sources: String)//Метод , который отвечает за добавление новых ресурсов.
+getName():String//реализуется "выбросом" исключения (как метод save)
+setName(name:String)//реализуется "выбросом" исключения (как метод save)
+getStart():Date//реализуется "выбросом" исключения (как метод save)
+setStart(start:Date)//реализуется "выбросом" исключения (как метод save)
+getFinish():Date//реализуется "выбросом" исключения (как метод save)
+setFinish(finish:Date)//реализуется "выбросом" исключения (как метод save)
+getTaskList(): List<ITask> Метод , который возвращает список задач.
+setTaskList(List<ITask>) Метод , который принимает список задач

**Comment by SpaceProg** [comment]
Я возьму эту задачу, если никто не против

**Comment by SpaceProg** [comment]
George,

а какой смысл реализовывать getStart() и др. методы выбросом исключений, если можно просто сразу реализовать метод, как положено (устанавливать дату, возвращать дату и т.п.)? На мой взгляд, на данном этапе это имеет смысл только для методов load/save и exportResources/importResources, т.к. сейчас мы их точно не будем реализовывать (хотя это не сложно в принципе).

**Comment by GeorgeSemenov** [comment]
Действительно , моя ошибка. Извиняюсь.
