### ISSUE TITLE
Создание класса TaskController в пакете Сontroller

### ISSUE THREAD

**Issue by GeorgeSemenov** [khasang/Cachoeira#21]
Написать класс TaskController — класс(можно сделать через интерфейс , как практикует Надежда) , имеющий следующие методы:
    addTask ()- добавляет новую задачу , вызывает метод setProperties() [см. ниже]. Также после его выполнения интерфейс должен обновиться , чтобы было видно , что добавилась новая задача.
    removeTask(task:ITask) - удаляет задачу , после его выполнения интерфейс должен обновиться , чтобы было видно , что задача удалилась.
    аddNewRowInTaskList () - метод , который позволяет  добавить новую колонку в список задач из контекстного меню, вызывает метод addNewRow(nameRow:String)[пока не созданный] класса Project , после его выполнения интерфейс должен обновиться , чтобы было видно , что добавилась новая колонка .
    setProperties() — позволяет вызвать окошко свойств задачи и редактировать их вызывает метод initTask()[пока не созданный] класса Task - который инициализирует задачу (имя + время начала + время конца + используемый ресурс + % выполнения).

**Comment by arc-en-ciel** [comment]
Давайте я возьму)
