### ISSUE TITLE
Прокачать вьюшку (контекстное меню "добавить задачу","св-ва задачи","удалить задачу")

### ISSUE THREAD

**Issue by GeorgeSemenov** [khasang/Cachoeira#22]
Реализовать на вьюхе возможность вызывать контекстное меню в котором будут пункты :
1)«Добавить задачу» , и привязать к ней соответствующий функционал (addTask() см задачу №21)
2)«Свойства задачи» - данный пункт должен появляться при нажатии правой кнопкой мыши на задаче , при его нажатии должен срабатывать initTask()
3)«Удалить задачу» - данный пункт должен появляться при нажатии правой кнопкой мыши     на задаче , при его нажатии должен срабатывать deleteTask(task:ITask)  см задачу №21.

**Comment by DmitriyCiglincev** [comment]
Попробую сделать, постараюсь не затягивать. Если что, пишите, кричите, кидайте такпками =) Будут вопросы, буду писать ))

**Comment by GeorgeSemenov** [comment]
Замётано.
