### ISSUE TITLE
UI Mockups

### ISSUE THREAD

**Issue by Raenar4k** [khasang/Cachoeira#4]

**Comment by Raenar4k** [comment]
r1.1_v1 (Roadmap 1.1, version 1):
![c_ui1](https://cloud.githubusercontent.com/assets/13849790/9701229/15f210a0-5420-11e5-9608-ee8e33d0424b.png)

**Comment by Raenar4k** [comment]
r1.1_v2
![c_ui2](https://cloud.githubusercontent.com/assets/13849790/9701235/5f868eda-5420-11e5-818d-1d45928689b4.png)

**Comment by Raenar4k** [comment]
r1.1_v3
![c_ui3](https://cloud.githubusercontent.com/assets/13849790/9701238/6e04721a-5420-11e5-959b-f0a2e685dcd5.png)

**Comment by DmitriyCiglincev** [comment]
Главная форма "Задачи" 
![default](https://cloud.githubusercontent.com/assets/9450839/9706600/574e467c-54f2-11e5-8133-d24758b7f9a2.png)

Главная форма "Ресурсы"
![default](https://cloud.githubusercontent.com/assets/9450839/9706602/64a07cb4-54f2-11e5-9390-bde4d57394b5.png)

**Comment by DmitriyCiglincev** [comment]
Согласно ТЗ v.1.1
Задачи V4
![v4](https://cloud.githubusercontent.com/assets/9450839/9960793/69c19638-5e25-11e5-8b8b-bc9a08fdcf29.png)
Ресурсы V4
![v4](https://cloud.githubusercontent.com/assets/9450839/9960794/69c435dc-5e25-11e5-9571-f66505ba4577.png)
Контекстные меню
![contextv4](https://cloud.githubusercontent.com/assets/9450839/9960792/69846240-5e25-11e5-9023-2f8fc801da8b.png)

**Comment by ghost** [comment]
![mockup 0922](https://cloud.githubusercontent.com/assets/13707635/10016150/a32f48ba-612d-11e5-9a79-5700b68a0b37.jpg)
