### ISSUE TITLE
Пофиксить невозможность открепить задачи.

### ISSUE THREAD

**Issue by GeorgeSemenov** [khasang/Cachoeira#50]
Дело в том что если создать более одного ресурса и к нему прикрепить задачи , то открепить их уже не удастся , они так и буду помечены , как привязанные к этому ресурсу , пока его не убьют или не найдут кого-нибудь получше.

**Comment by GeorgeSemenov** [comment]
Fixed by Truesik #56

**Comment by hackmetwice** [comment]
в текущей версии на Git hub ошибка наблюдается!!!
